# Generated by Django 5.0.3 on 2025-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=20)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('prediction', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
