# Generated by Django 5.0.3 on 2025-10-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetectionresult',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
