# Generated by Django 5.0.3 on 2025-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetectionresult',
            name='image',
        ),
        migrations.AddField(
            model_name='plantdetectionresult',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantdetectionresult',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdetectionresult',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetectionresult',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
