# Generated by Django 5.0.3 on 2025-10-27 15:01

# plant_detection/migrations/0003_populate_image_fields.py
from django.db import migrations
import os

def populate_image_fields(apps, schema_editor):
    PlantDetectionResult = apps.get_model('plant_detection', 'PlantDetectionResult')
    
    # Get all existing detection records
    detections = PlantDetectionResult.objects.all()
    
    print(f"🔄 Populating image fields for {detections.count()} existing records...")
    
    for detection in detections:
        try:
            # Set default values for existing records
            if not detection.image_name:
                # Extract filename from the image path if it exists
                if hasattr(detection, 'image') and detection.image:
                    detection.image_name = os.path.basename(detection.image.name)
                else:
                    detection.image_name = f"detection_{detection.id}.jpg"
            
            if not detection.image_content_type:
                detection.image_content_type = "image/jpeg"
            
            # For existing records, we can't populate image_data from file system
            # since we removed the image field. They'll remain null.
            # New detections will have image_data populated.
            
            detection.save()
            print(f"✅ Updated detection {detection.id}")
            
        except Exception as e:
            print(f"❌ Error updating detection {detection.id}: {e}")
            continue

def reverse_populate(apps, schema_editor):
    # Reverse function - not needed for this migration
    # We don't want to remove the data we just populated
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('plant_detection', '0002_remove_plantdetectionresult_image_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_image_fields, reverse_populate),
    ]
